<?php

/* The WP_List_Table base class is not included by default, so we need to load it */
if (!class_exists('WP_List_Table')) {
    require_once ABSPATH . 'wp-admin/includes/class-wp-list-table.php';
}

/**
 * This class handles the table for the manage snippets menu
 *
 *
 * @package WPD_snippets
 */
class WPDListTableClass extends WP_List_Table
{


//    define data set for WP list tal=ble


//prepare items
public function prepare_items()
{
    parent::prepare_items(); // TODO: Change the autogenerated stub
}
//get columns
}

function wpd_list_table_layout()
{
    if (class_exists('WPDListTableClass')) {
        $wpdSnippetsList = new WPDListTableClass();
        $wpdSnippetsList->prepare_items();
        $wpdSnippetsList->display();
    }
//    CAlling prepare item
}
